# Generated by Django 5.2.6 on 2025-09-25 15:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('Cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('Id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_compra', models.CharField(choices=[('CARNE', 'Carne'), ('INSUMO', 'Insumo')], default='INSUMO', max_length=10)),
                ('Precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha_compra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('Id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desposte',
            fields=[
                ('Id_desposte', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Unidades', models.PositiveIntegerField(default=1)),
                ('Peso_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Merma', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('Id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('Cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('insumo', 'Insumo'), ('carne', 'Carne')], default='insumo', max_length=20)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miAplicacion.categoria')),
                ('Id_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='LoteCarne',
            fields=[
                ('Id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_medias_res', models.IntegerField(default=0)),
                ('despostadas', models.IntegerField(default=0)),
                ('merma_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_llegada', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='miAplicacion.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('Id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Precio_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.categoria')),
                ('Id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='miAplicacion.compra')),
                ('Id_insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.insumo')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miAplicacion.lotecarne')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Corte', models.CharField(max_length=100)),
                ('Precio_kilo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_mayor_x_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('en_promocion', models.BooleanField(default=False)),
                ('stock_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fecha_ingreso_elaboracion', models.DateTimeField()),
                ('fecha_vencimiento', models.DateField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('Id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='CorteDesposte',
            fields=[
                ('Id_corte', models.AutoField(primary_key=True, serialize=False)),
                ('Peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Id_desposte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='miAplicacion.desposte')),
                ('Id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('Id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('Precio_oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha_inicio', models.DateTimeField()),
                ('Fecha_fin', models.DateTimeField()),
                ('Id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='Id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.proveedores'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_venta', models.CharField(choices=[('mayor', 'Mayor'), ('menor', 'Menor'), ('promocion', 'Promocion')], max_length=50)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=50)),
                ('Estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=50)),
                ('Fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('Id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('Id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('Precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.producto')),
                ('Id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.venta')),
            ],
        ),
    ]
