# Generated by Django 5.1.1 on 2025-09-26 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad en Stock')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Unitario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('supply_type', models.CharField(choices=[('bread', 'Pan'), ('wood', 'Leña'), ('charcoal', 'Carbón'), ('bags', 'Bolsas'), ('condiments', 'Condimentos'), ('other', 'Otros')], default='other', max_length=20, verbose_name='Tipo de Insumo')),
                ('supplier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.proveedores', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='supply_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.supply'),
        ),
    ]
