# Generated by Django 5.1.1 on 2025-11-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0002_supply_detalle_compra_supply_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='Cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
