# Generated by Django 5.1.1 on 2025-11-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0003_alter_detalle_venta_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promociones',
            options={'ordering': ['-Fecha_inicio'], 'verbose_name': 'Promoción', 'verbose_name_plural': 'Promociones'},
        ),
        migrations.AddField(
            model_name='promociones',
            name='cantidad_minima',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad mínima para aplicar promoción (kg)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promociones',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la promoción', null=True),
        ),
        migrations.AddField(
            model_name='promociones',
            name='descuento_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de descuento (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='promociones',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('programada', 'Programada'), ('vencida', 'Vencida')], default='activa', max_length=20),
        ),
        migrations.AddField(
            model_name='promociones',
            name='tipo_promocion',
            field=models.CharField(choices=[('rebaja_unidad', 'Rebaja por Unidad'), ('mayorista', 'Mayorista'), ('descuento_porcentaje', 'Descuento Porcentaje'), ('2x1', '2x1'), ('oferta_especial', 'Oferta Especial')], default='rebaja_unidad', max_length=30),
        ),
        migrations.AlterField(
            model_name='promociones',
            name='Id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='miAplicacion.producto'),
        ),
    ]
