# Generated by Django 5.1.1 on 2025-11-04 23:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0004_alter_promociones_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'Kilogramo'), ('BOLSA', 'Bolsa'), ('UNIDAD', 'Unidad'), ('LTS', 'Litros'), ('GR', 'Gramos'), ('PAQUETE', 'Paquete'), ('DOCENA', 'Docena'), ('MEDIA_RES', 'Media Res')], default='KG', help_text='Unidad de medida para ventas e inventario', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stock disponible en la unidad de medida seleccionada', max_digits=10),
        ),
    ]
