# Generated by Django 5.1.1 on 2025-11-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0005_producto_unidad_medida_alter_producto_stock_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='unidades_permitidas',
            field=models.CharField(choices=[('KG', 'Solo Kilogramos'), ('UNIDAD', 'Solo Unidades'), ('BOLSA', 'Solo Bolsas'), ('LTS', 'Solo Litros'), ('PESO', 'Unidades de Peso (KG, GR)'), ('VOLUMEN', 'Unidades de Volumen (LTS)'), ('EMPAQUETADO', 'Unidades Empaquetadas (BOLSA, PAQUETE, DOCENA)'), ('TODAS', 'Todas las Unidades')], default='TODAS', help_text='Define qué unidades de medida se pueden usar para productos de esta categoría', max_length=20),
        ),
    ]
