# Generated by Django 5.1.1 on 2025-11-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0006_categoria_unidades_permitidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Nombre',
            field=models.CharField(blank=True, help_text='Nombre general del producto', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Corte',
            field=models.CharField(blank=True, help_text='Corte específico (para carnes/chacinados)', max_length=100, null=True),
        ),
    ]
