# Generated by Django 5.1.1 on 2025-11-05 01:03

from django.db import migrations


def copiar_corte_a_nombre(apps, schema_editor):
    """Copia el valor de Corte a Nombre para productos existentes"""
    Producto = apps.get_model('miAplicacion', 'Producto')
    for producto in Producto.objects.all():
        if not producto.Nombre and producto.Corte:
            producto.Nombre = producto.Corte
            producto.save()


def revertir(apps, schema_editor):
    """No hace nada al revertir"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0007_producto_nombre_alter_producto_corte'),
    ]

    operations = [
        migrations.RunPython(copiar_corte_a_nombre, revertir),
    ]
