# Generated by Django 5.1.1 on 2025-11-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0008_auto_20251104_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_ingreso_elaboracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Opcional: solo para productos perecederos', null=True),
        ),
    ]
