# Generated by Django 5.1.1 on 2025-12-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0009_alter_producto_fecha_ingreso_elaboracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='unidades_permitidas',
            field=models.CharField(choices=[('KG', 'Kilogramos'), ('UNIDAD', 'Unidad'), ('LTS', 'Litros')], default='KG', help_text='Define qué unidades de medida se pueden usar para productos de esta categoría', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'Kilogramo'), ('UNIDAD', 'Unidad'), ('LTS', 'Litros')], default='KG', help_text='Unidad de medida para ventas e inventario', max_length=20),
        ),
    ]
