# Generated by Django 5.2.8 on 2025-11-27 20:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0009_alter_producto_fecha_ingreso_elaboracion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('Id_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_producida', models.DecimalField(decimal_places=2, help_text='Cantidad final producida (kg o unidades).', max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('merma', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Merma en las mismas unidades que cantidad_producida (kg o unidades).', max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionDetalle',
            fields=[
                ('Id_produccion_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('item_tipo', models.CharField(choices=[('insumo', 'Insumo'), ('producto', 'Producto'), ('producto_final', 'Producto Final')], max_length=30)),
                ('item_insumo', models.IntegerField(blank=True, null=True)),
                ('item_producto', models.IntegerField(blank=True, null=True)),
                ('cantidad_usada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='miAplicacion.produccion')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('Id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('rendimiento_por_lote', models.DecimalField(decimal_places=2, help_text='Cantidad (kg o unidades) que produce el lote base', max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='miAplicacion.producto')),
            ],
        ),
        migrations.AddField(
            model_name='produccion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='miAplicacion.receta'),
        ),
        migrations.CreateModel(
            name='RecetaItem',
            fields=[
                ('Id_receta_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_por_rendimiento', models.DecimalField(decimal_places=3, help_text='Cantidad para 1 lote base (mismo unidad que rendimiento).', max_digits=10)),
                ('tipo_item', models.CharField(choices=[('insumo', 'Insumo'), ('producto', 'Producto')], default='insumo', max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receta_items', to='miAplicacion.insumo')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receta_items_as_ingredient', to='miAplicacion.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='miAplicacion.receta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
