# Generated by Django 5.2 on 2026-02-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0010_produccion_producciondetalle_receta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'Kilogramo'), ('GR', 'Gramos'), ('MT', 'Metros'), ('ML', 'Mililitros'), ('LTS', 'Litros'), ('UNIDAD', 'Unidad'), ('BOLSA', 'Bolsa'), ('PAQUETE', 'Paquete'), ('DOCENA', 'Docena')], default='KG', help_text='Unidad de medida para este insumo', max_length=20),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
