# Generated by Django 5.1.1 on 2025-12-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0010_alter_categoria_unidades_permitidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='unidades_permitidas',
            field=models.CharField(choices=[('KG', 'Kilogramos'), ('UNIDAD_LTS', 'Unidades/Litros')], default='KG', help_text='Define qué unidades de medida se pueden usar para productos de esta categoría', max_length=20),
        ),
    ]
