# Generated by Django 5.1.1 on 2025-12-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0011_alter_categoria_unidades_permitidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
