# Generated by Django 5.1.1 on 2025-12-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0012_cliente_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Ciudad',
        ),
        migrations.AddField(
            model_name='compra',
            name='Estado',
            field=models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='Forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota de Crédito')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='unidades_permitidas',
            field=models.CharField(choices=[('KG', 'Solo Kilogramos'), ('UNIDAD', 'Solo Unidades'), ('BOLSA', 'Solo Bolsas'), ('LTS', 'Solo Litros'), ('PESO', 'Unidades de Peso (KG, GR)'), ('VOLUMEN', 'Unidades de Volumen (LTS)'), ('EMPAQUETADO', 'Unidades Empaquetadas (BOLSA, PAQUETE, DOCENA)'), ('TODAS', 'Todas las Unidades')], default='TODAS', help_text='Define qué unidades de medida se pueden usar para productos de esta categoría', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Tipo_compra',
            field=models.CharField(choices=[('mayor', 'Mayor'), ('menor', 'Menor')], default='menor', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'Kilogramo'), ('BOLSA', 'Bolsa'), ('UNIDAD', 'Unidad'), ('LTS', 'Litros'), ('GR', 'Gramos'), ('PAQUETE', 'Paquete'), ('DOCENA', 'Docena'), ('MEDIA_RES', 'Media Res')], default='KG', help_text='Unidad de medida para ventas e inventario', max_length=20),
        ),
    ]
