# Generated by Django 5.2.8 on 2025-12-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0013_remove_cliente_ciudad_compra_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='sale_price',
            field=models.IntegerField(default=0, verbose_name='Venta al Público'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de Costo'),
        ),
    ]
