# Generated by Django 5.2.8 on 2025-12-04 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0014_supply_sale_price_alter_supply_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='sale_price',
        ),
    ]
