# Generated by Django 5.2.8 on 2025-12-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0015_remove_supply_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='supply',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Recepción'),
        ),
        migrations.AddField(
            model_name='supply',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('unidad', 'Unidad'), ('caja', 'Caja'), ('bolsa', 'Bolsa')], default='unidad', max_length=20, verbose_name='Unidad de Medida'),
        ),
    ]
