# Generated by Django 5.2.8 on 2026-02-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0016_supply_cantidad_supply_fecha_recepcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='Fecha_compra',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Tipo_compra',
            field=models.CharField(choices=[('mayor', 'Mayor'), ('menor', 'Menor'), ('CARNE', 'Carne'), ('INSUMO', 'Insumo')], default='menor', max_length=10),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_type',
            field=models.CharField(choices=[('bread', 'Pan'), ('wood', 'Leña'), ('charcoal', 'Carbón'), ('bags', 'Bolsas'), ('condiments', 'Condimentos'), ('butcher_supplies', 'Art. de Carnicería'), ('other', 'Otros')], default='other', max_length=20, verbose_name='Tipo de Insumo'),
        ),
    ]
