# Generated by Django 5.2.8 on 2026-02-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0016_supply_cantidad_supply_fecha_recepcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='unidades_permitidas',
            field=models.CharField(choices=[('KG', 'Solo Kilogramos'), ('UNIDAD', 'Solo Unidades'), ('BOLSA', 'Solo Bolsas'), ('LTS', 'Solo Litros'), ('UNIDAD_LTS', 'Unidades y Litros'), ('PESO', 'Unidades de Peso (KG, GR)'), ('VOLUMEN', 'Unidades de Volumen (LTS)'), ('EMPAQUETADO', 'Unidades Empaquetadas (BOLSA, PAQUETE, DOCENA)'), ('TODAS', 'Todas las Unidades')], default='TODAS', help_text='Define qué unidades de medida se pueden usar para productos de esta categoría', max_length=20),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_type',
            field=models.CharField(choices=[('bread', 'Pan'), ('wood', 'Leña'), ('charcoal', 'Carbón'), ('bags', 'Bolsas'), ('condiments', 'Condimentos'), ('butcher_supplies', 'Art. de Carnicería'), ('other', 'Otros')], default='other', max_length=20, verbose_name='Tipo de Insumo'),
        ),
    ]
