# Generated by Django 5.2.8 on 2026-02-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0011_insumo_unidad_medida_alter_insumo_nombre'),
        ('miAplicacion', '0017_fecha_compra_auto_now'),
    ]

    operations = [
    ]
