# Generated by Django 5.2.8 on 2026-02-22 20:13

from django.db import migrations, models


def kg_to_gr_data(apps, schema_editor):
    """Migrar datos existentes: KG → GR en productos y categorías."""
    Producto = apps.get_model('miAplicacion', 'Producto')
    Categoria = apps.get_model('miAplicacion', 'Categoria')

    # Productos: cambiar unidad_medida de KG a GR
    Producto.objects.filter(unidad_medida='KG').update(unidad_medida='GR')

    # Categorías: cambiar unidades_permitidas de KG a GR
    Categoria.objects.filter(unidades_permitidas='KG').update(unidades_permitidas='GR')


def gr_to_kg_data(apps, schema_editor):
    """Revertir: GR → KG."""
    Producto = apps.get_model('miAplicacion', 'Producto')
    Categoria = apps.get_model('miAplicacion', 'Categoria')
    Producto.objects.filter(unidad_medida='GR').update(unidad_medida='KG')
    Categoria.objects.filter(unidades_permitidas='GR').update(unidades_permitidas='KG')


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0017_alter_categoria_unidades_permitidas_and_more'),
    ]

    operations = [
        # Primero migrar datos (mientras KG aún es un choice válido en la BD)
        migrations.RunPython(kg_to_gr_data, gr_to_kg_data),
        # Después cambiar los choices del schema
        migrations.AlterField(
            model_name='categoria',
            name='unidades_permitidas',
            field=models.CharField(choices=[('GR', 'Solo Gramos'), ('UNIDAD', 'Solo Unidades'), ('BOLSA', 'Solo Bolsas'), ('LTS', 'Solo Litros'), ('UNIDAD_LTS', 'Unidades y Litros'), ('PESO', 'Unidades de Peso (GR)'), ('VOLUMEN', 'Unidades de Volumen (LTS)'), ('EMPAQUETADO', 'Unidades Empaquetadas (BOLSA, PAQUETE, DOCENA)'), ('TODAS', 'Todas las Unidades')], default='TODAS', help_text='Define qué unidades de medida se pueden usar para productos de esta categoría', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('GR', 'Gramos'), ('BOLSA', 'Bolsa'), ('UNIDAD', 'Unidad'), ('LTS', 'Litros'), ('PAQUETE', 'Paquete'), ('DOCENA', 'Docena'), ('MEDIA_RES', 'Media Res')], default='GR', help_text='Unidad de medida para ventas e inventario', max_length=20),
        ),
    ]
