# Generated by Django 5.2.8 on 2026-02-22 20:31

from django.db import migrations, models


def gr_to_kg_data(apps, schema_editor):
    """Revertir datos: GR → KG en productos y categorías."""
    Producto = apps.get_model('miAplicacion', 'Producto')
    Categoria = apps.get_model('miAplicacion', 'Categoria')
    Producto.objects.filter(unidad_medida='GR').update(unidad_medida='KG')
    Categoria.objects.filter(unidades_permitidas='GR').update(unidades_permitidas='KG')


def kg_to_gr_data(apps, schema_editor):
    """Forward (por si se revierte esta migración)."""
    Producto = apps.get_model('miAplicacion', 'Producto')
    Categoria = apps.get_model('miAplicacion', 'Categoria')
    Producto.objects.filter(unidad_medida='KG').update(unidad_medida='GR')
    Categoria.objects.filter(unidades_permitidas='KG').update(unidades_permitidas='GR')


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0018_kg_to_gr'),
    ]

    operations = [
        # Primero revertir datos
        migrations.RunPython(gr_to_kg_data, kg_to_gr_data),
        # Después revertir schema/choices
        migrations.AlterField(
            model_name='categoria',
            name='unidades_permitidas',
            field=models.CharField(choices=[('KG', 'Solo Kilogramos'), ('UNIDAD', 'Solo Unidades'), ('BOLSA', 'Solo Bolsas'), ('LTS', 'Solo Litros'), ('UNIDAD_LTS', 'Unidades y Litros'), ('PESO', 'Unidades de Peso (KG, GR)'), ('VOLUMEN', 'Unidades de Volumen (LTS)'), ('EMPAQUETADO', 'Unidades Empaquetadas (BOLSA, PAQUETE, DOCENA)'), ('TODAS', 'Todas las Unidades')], default='TODAS', help_text='Define qué unidades de medida se pueden usar para productos de esta categoría', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'Kilogramo'), ('BOLSA', 'Bolsa'), ('UNIDAD', 'Unidad'), ('LTS', 'Litros'), ('GR', 'Gramos'), ('PAQUETE', 'Paquete'), ('DOCENA', 'Docena'), ('MEDIA_RES', 'Media Res')], default='KG', help_text='Unidad de medida para ventas e inventario', max_length=20),
        ),
    ]
