# Generated by Django 5.2.8 on 2026-03-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0018_merge_20260223_2302'),
        ('miAplicacion', '0019_revert_gr_to_kg'),
    ]

    operations = [
    ]
