# Generated by Django 5.1.1 on 2026-03-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0020_merge_0018_merge_20260223_2302_0019_revert_gr_to_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_compra',
            name='supply_id',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='unidades_permitidas',
            field=models.CharField(choices=[('UNIDAD', 'Solo Unidades'), ('BOLSA', 'Solo Bolsas'), ('LTS', 'Solo Litros'), ('UNIDAD_LTS', 'Unidades y Litros'), ('VOLUMEN', 'Unidades de Volumen (LTS)'), ('EMPAQUETADO', 'Unidades Empaquetadas (BOLSA, PAQUETE, DOCENA)')], default='UNIDAD', help_text='Define qué unidades de medida se pueden usar para productos de esta categoría', max_length=20),
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
    ]
