# Generated by Django 5.2.8 on 2026-03-05 14:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0021_remove_detalle_compra_supply_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='unidades_permitidas',
            field=models.CharField(choices=[('UNIDAD_KG', 'Unidades y Kilogramos'), ('UNIDAD_PAQUETE', 'Unidades y Paquetes')], default='UNIDAD_KG', help_text='Define qué unidades de medida se pueden usar para productos de esta categoría', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stock interno: en gramos si la unidad es KG, cantidad directa para UNIDAD/PAQUETE', max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'Kilogramo'), ('UNIDAD', 'Unidad'), ('PAQUETE', 'Paquete')], default='KG', help_text='Unidad de medida para ventas e inventario', max_length=20),
        ),
    ]
