# Generated by Django 5.2.8 on 2026-03-05 14:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0023_convertir_stock_kg_a_gramos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='Cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Stock interno: en gramos si la unidad es KG, cantidad directa para UNIDAD/PAQUETE', max_digits=12),
        ),
    ]
