# Generated by Django 5.2.8 on 2026-03-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0024_alter_detalle_venta_cantidad_alter_producto_stock_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_mayor_x_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional: precio para ventas mayoristas. Si no se define, no se aplica descuento.', max_digits=10, null=True),
        ),
    ]
