# Generated by Django 5.2.8 on 2026-03-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0025_alter_producto_precio_mayor_x_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto ya pagado al proveedor por esta compra', max_digits=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='Tipo_compra',
            field=models.CharField(choices=[('CARNE', 'Carne'), ('INSUMO', 'Insumo')], default='CARNE', max_length=10),
        ),
    ]
