# Generated by Django 5.2.8 on 2026-03-05 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0026_compra_monto_pagado_alter_compra_tipo_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desposte',
            name='Id_categoria',
        ),
        migrations.AddField(
            model_name='desposte',
            name='Id_insumo',
            field=models.ForeignKey(blank=True, help_text='Insumo de carne a despostar', null=True, on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.insumo'),
        ),
    ]
